services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped

    ports:
      - "${PORT:-3000}:3000"

    environment:
      BASE_URL: ${BASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URI: ${DATABASE_URI}
      AIOSTREAMS_AUTH: ${AIOSTREAMS_AUTH}
      TRUSTED_UUIDS: ${TRUSTED_UUIDS}

    volumes:
      - aiostreams_data:/app/data

volumes:
  aiostreams_data:
